# Generated by Django 2.2.9 on 2020-02-29 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='Github',
            field=models.URLField(null=True),
        ),
    ]
